# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180509_2307'),
        ('exercises', '0004_auto_20180430_1501'),
    ]

    operations = [
    ]
