# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Video'),
        ),
    ]
