# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_exercise_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.TextField(blank=True, max_length=200, verbose_name='Video'),
        ),
    ]
