# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-14 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_auto_20180514_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Video'),
        ),
    ]
