# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-17 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_auto_20180514_1644'),
        ('nutrition', '0005_auto_20180511_1421'),
        ('nutrition', '0006_auto_20180515_0718'),
    ]

    operations = [
    ]
