# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_auto_20180430_1501'),
        ('gym', '0007_auto_20180502_1942'),
    ]

    operations = [
    ]
