# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-11 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180510_2000'),
        ('core', '0011_merge'),
    ]

    operations = [
    ]
