# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-15 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_merge'),
        ('manager', '0010_workoutsession_workout_log'),
    ]

    operations = [
    ]
