# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-17 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20180515_0706'),
        ('manager', '0012_auto_20180514_1644'),
        ('manager', '0012_auto_20180511_1421'),
        ('manager', '0012_merge'),
    ]

    operations = [
    ]
